---
application:
  title: 'PWiki'
  logo: ''
  favicon: ''
  repository: '/Users/parkerwilliams/GitRepos/plain-text-table'
  docSubdir: ''
  remote: 'origin'
  pushInterval: 30
  secret: change me
  git: git
  skipGitCheck: false
  loggingMode: 1
  pedanticMarkdown: true
  gfmBreaks: true
  staticWhitelist: '/\.png$/i, /\.jpg$/i, /\.gif$/i'
  proxyPath: ''
authentication:
  google:
    enabled: false
    clientId: replace me with the real value
    clientSecret: replace me with the real value
    redirectURL: ''
  github:
    enabled: true
    clientId: 092a36b02a48dced7ec0
    clientSecret: 418775051309114b03d810d60afd1516416bbef5
    redirectURL: '/auth/github/callback'
  ldap:
    enabled: false
    url: 'ldap://example.org:389'
    bindDn: ''
    bindCredentials: ''
    searchBase: 'ou=people,dc=example,dc=org'
    searchFilter: '(uid={{username}})'
    searchAttributes: ''
  local:
    enabled: false
    accounts:
      - username: ''
        passwordHash: ''
        email: ''
features:
  markitup: false
  codemirror: true
  gravatar: true
server:
  hostname: pwill2.github.io
  port: 6067
  localOnly: false
  baseUrl: ''
  CORS:
    enabled: false
    allowedOrigin: '*'
authorization:
  anonRead: true
  validMatches: .+
  emptyEmailMatches: true
pages:
  index: Home
  title:
    fromFilename: true
    fromContent: false
    asciiOnly: false
    lowercase: false
  itemsPerPage: 10
customizations:
  sidebar: _sidebar.md
  footer: _footer.md
  style: _style.css
  script: _script.js